### PR TITLE
Fixed form dropdown not dismissing when post is successful

### LINKED ISSUE #40: Form dropdown isn't hidden when post is successful

### PR DESCRIPTION
**Pull request by Rukkaitto**
Fixes #40

### CODE REVIEW

File: lib/features/post/widgets/form_widget/handlers.dart [hunk 1]
```diff
@@ -59,6 +60,7 @@ extension FormWidgetHandlers on FormWidget {
                 file: form.file,
               );
           context.read<PostFormCubit>().setVisible(false);
+          context.read<ThreadsCubit>().getThreads(board, sort!);
```
Comment (mitchross) [inline lib/features/post/widgets/form_widget/handlers.dart:63]: sort is a nullable property on line 37, then you are forcing non null here. Either make Sort required or provide a default if null.

File: lib/features/post/widgets/form_widget/widget.dart [hunk 2]
```diff
@@ -9,9 +9,10 @@ class FormWidget extends StatelessWidget {
   final Duration animationDuration = const Duration(milliseconds: 300);
 
   final Board board;
+  final Sort? sort;
```
Comment (mitchross) [inline lib/features/post/widgets/form_widget/widget.dart:12]: same comment as above

**Review by mitchross — APPROVED** [review]
